name: CI pipeline

on:
  pull_request:
    branches:
      - develop
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_STAGING_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_STAGING_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -e .

      - name: Fix ruamel.yaml issue
        run: |
          pip install "ruamel.yaml<0.18"

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Deploy integration test [staging environment]
        run: |
          dbx deploy --jobs=STAGING-booking-sample-integration-test --environment=staging --files-only

      - name: Run integration test [staging environment]
        run: |
          dbx launch --job=STAGING-booking-sample-integration-test --environment=staging --as-run-submit --trace

      - name: Deploy STAGING-booking-initial-model-train-register job [STAGING environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=STAGING-booking-initial-model-train-register --environment=staging

      - name: Deploy STAGING-booking-model-inference-batch job [STAGING environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=STAGING-booking-model-inference-batch --environment=staging
