name: Release pipeline

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_STAGING_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_STAGING_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Fix ruamel.yaml issue
        run: |
          pip install "ruamel.yaml<0.18"

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt


      - name: Deploy PROD-booking-initial-model-train-register job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-booking-initial-model-train-register --environment=prod

      - name: Deploy PROD-booking-model-inference-batch job [prod environment]
        run: |
          dbx deploy --deployment-file conf/deployment.yml --jobs=PROD-booking-model-inference-batch --environment=prod
